//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCinHereForMastodon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerDomain {
            get {
                return ((string)(this["ServerDomain"]));
            }
            set {
                this["ServerDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string APIKey {
            get {
                return ((string)(this["APIKey"]));
            }
            set {
                this["APIKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStart {
            get {
                return ((bool)(this["AutoStart"]));
            }
            set {
                this["AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootPublicJoin {
            get {
                return ((bool)(this["TootPublicJoin"]));
            }
            set {
                this["TootPublicJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootPublicJoinURL {
            get {
                return ((bool)(this["TootPublicJoinURL"]));
            }
            set {
                this["TootPublicJoinURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootFriendsPlusJoin {
            get {
                return ((bool)(this["TootFriendsPlusJoin"]));
            }
            set {
                this["TootFriendsPlusJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootFriendsPlusJoinURL {
            get {
                return ((bool)(this["TootFriendsPlusJoinURL"]));
            }
            set {
                this["TootFriendsPlusJoinURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootFriendsOnlyJoin {
            get {
                return ((bool)(this["TootFriendsOnlyJoin"]));
            }
            set {
                this["TootFriendsOnlyJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootFriendsOnlyJoinURL {
            get {
                return ((bool)(this["TootFriendsOnlyJoinURL"]));
            }
            set {
                this["TootFriendsOnlyJoinURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootGroupJoin {
            get {
                return ((bool)(this["TootGroupJoin"]));
            }
            set {
                this["TootGroupJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootGroupJoinWorldName {
            get {
                return ((bool)(this["TootGroupJoinWorldName"]));
            }
            set {
                this["TootGroupJoinWorldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootInvitePlusJoin {
            get {
                return ((bool)(this["TootInvitePlusJoin"]));
            }
            set {
                this["TootInvitePlusJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootInvitePlusJoinWorldName {
            get {
                return ((bool)(this["TootInvitePlusJoinWorldName"]));
            }
            set {
                this["TootInvitePlusJoinWorldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootPrivateJoin {
            get {
                return ((bool)(this["TootPrivateJoin"]));
            }
            set {
                this["TootPrivateJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootPrivateJoinWorldName {
            get {
                return ((bool)(this["TootPrivateJoinWorldName"]));
            }
            set {
                this["TootPrivateJoinWorldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootLogout {
            get {
                return ((bool)(this["TootLogout"]));
            }
            set {
                this["TootLogout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TootPublishType {
            get {
                return ((int)(this["TootPublishType"]));
            }
            set {
                this["TootPublishType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("今ここにいます。")]
        public string TootText {
            get {
                return ((string)(this["TootText"]));
            }
            set {
                this["TootText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotTootSpecifyWorldJoin {
            get {
                return ((bool)(this["NotTootSpecifyWorldJoin"]));
            }
            set {
                this["NotTootSpecifyWorldJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaskSpecifyWorldName {
            get {
                return ((bool)(this["MaskSpecifyWorldName"]));
            }
            set {
                this["MaskSpecifyWorldName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SpecifyWorldList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SpecifyWorldList"]));
            }
            set {
                this["SpecifyWorldList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootGroupPublicJoin {
            get {
                return ((bool)(this["TootGroupPublicJoin"]));
            }
            set {
                this["TootGroupPublicJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootGroupPublicJoinURL {
            get {
                return ((bool)(this["TootGroupPublicJoinURL"]));
            }
            set {
                this["TootGroupPublicJoinURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TootGroupPlusJoin {
            get {
                return ((bool)(this["TootGroupPlusJoin"]));
            }
            set {
                this["TootGroupPlusJoin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootGroupPlusJoinURL {
            get {
                return ((bool)(this["TootGroupPlusJoinURL"]));
            }
            set {
                this["TootGroupPlusJoinURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootError {
            get {
                return ((bool)(this["TootError"]));
            }
            set {
                this["TootError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TootDateTime {
            get {
                return ((bool)(this["TootDateTime"]));
            }
            set {
                this["TootDateTime"] = value;
            }
        }
    }
}
